[package]
name = "qlhighlight"
version = "0.1.0"
authors = ["Bastian Rinsche <bastian.rinsche@gmail.com>"]

[lib]
name = "qlhighlight"
crate-type = ["staticlib"]

[dependencies]
core-foundation = "0.5"
core-foundation-sys = "0.5"
syntect = "2"
